chore: add INVERT_LOOPCTRL mutation
go-gremlins/gremlins pull request #159
Opened 2022-09-08 08:02 UTC by alessio-perugini

## Proposed changes

Implement #136 invert loop break/continue

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/go-gremlins/gremlins/docs/CONTRIBUTING.md) doc
- [x] Lint and unit tests pass locally with my changes (`make all`)
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [x] Any dependent changes have been merged and published in downstream modules

## Further comments

2022-09-08 08:33 UTC, k3rn31 commented
Hello @alessio-perugini, thanks for you PR. I enabled the CI for you.

2022-09-08 08:35 UTC, alessio-perugini commented
@k3rn31 thank you. I run a simple test when the mutant generates an infinite loop and the result is a `TIMED OUT`. Are we okay with that?

2022-09-08 08:55 UTC, k3rn31 commented
@alessio-perugini I'd say it is to be expected in this kind of mutation. It is showing a brittle test case :)

As soon as you mark it as non draft we'll proceed with the review.

2022-09-09 04:57 UTC, k3rn31 requested changes
Thanks again for the PR. Everything looks good.
Since this kind of mutation can produce lots of unbound loops and, consequently, timeouts, it is maybe better to keep it disabled by default.
Could you please fix that and update the documentation accordingly?

Also, since every mutation increases testing times, we decided to keep all the new mutations disabled by default, leaving to the user the decision to enable them on the basis of project necessities. In the future we'll make some statistics to craft a better core set.

2022-09-09 04:57 UTC, k3rn31 commented on docs/docs/usage/mutations/invert_loop.md
> +_Invert loop control_ will perform inversions on control operations, which means a `continue` will become a `break`..
The sentence ends with two periods.

2022-09-09 07:25 UTC, k3rn31 approved these changes
Everything looks good, I'm going to merge this.

2022-09-09 07:30 UTC, merged